export const BELARUS_CITIES = [
    'Minsk',
    'Homyel’',
    'Vitsyebsk',
    'Mahilyow',
    'Hrodna',
    'Brest',
    'Babruysk',
    'Baranavichy',
    'Horad Barysaw',
    'Pinsk',
    'Orsha',
    'Mazyr',
    'Lida',
    'Salihorsk',
    'Navapolatsk',
    'Maladzyechna',
    'Polatsk',
    'Svyetlahorsk',
    'Slutsk',
    'Kobryn',
    'Slonim',
    'Vawkavysk',
    'Kalinkavichy',
    'Smarhon’',
    'Horki',
    'Asipovichy',
    'Dzyarzhynsk',
    'Byaroza',
    'Navahrudak',
    'Vilyeyka',
    'Krychaw',
    'Luninyets',
    'Mar’’ina Horka',
    'Pastavy',
    'Pruzhany',
    'Dobrush',
    'Hlybokaye',
    'Zaslawye',
    'Fanipal’',
    'Stowbtsy',
    'Ashmyany',
    'Ivanava',
    'Klimavichy',
    'Lahoysk',
    'Masty',
    'Drahichyn',
    'Astravyets',
    'Khoyniki',
    'Stolin',
    'Malaryta',
    'Mikashevichy',
    'Novalukoml’',
    'Haradok',
    'Lyuban’',
    'Klyetsk',
    'Byerazino',
    'Staryya Darohi',
    'Byelaazyorsk',
    'Uzda',
    'Baran’',
    'Kapyl’',
    'Mstsislaw',
    'Skidal’',
    'Byarozawka',
    'Valozhyn',
    'Pyetrykaw',
    'Byalynichy',
    'Talachyn',
    'Braslaw',
    'Buda-Kashalyova',
    'Krupki',
    'Vyetka',
    'Narowlya',
    'Kamyanyets',
    'Kirawsk',
    'Dzyatlava',
    'Slawharad',
    'Cherykaw',
    'Myory',
    'Kruhlaye',
    'Syanno',
    'Iwye',
    'Klichaw',
    'Myadzyel',
    'Vyerkhnyadzvinsk',
    'Dubrowna',
    'Svislach',
    'Davyd-Haradok',
    'Vysokaye',
    'Azyershchyna',
    'Kozyenki',
    'Vasilyevichy',
    'Turaw',
    'Hlushkavichy',
    'Babrovichy',
    'Vyalikiya Chuchavichy',
    'Novy Svyerzhan’',
    'Kosava',
    'Vyalikiya Lyepyasy',
    'Haradnaya',
    'Ramanavichy',
    'Dzisna',
    'Novaya Mysh',
    'Akhremawtsy',
    'Lakhva',
    'Khal’ch',
    'Nasilava',
    'Kavyerdzyaki',
    'Haradzyets',
    'Uza',
    'Salonaye',
    'Al’khowka',
    'Bronnaye',
    'Rudnya',
    'Andreyewshchyna',
    'Yakimovskaya Sloboda',
    'Tsishowka',
    'Lyubashava',
    'Horad Zhodzina',
    'Horad Pinsk',
    'Horad Smalyavichy',
    'Zhlobin',
    'Nyasvizh',
    'Horad Krychaw',
    'Horad Kobryn',
    'Horad Rechytsa',
    'Rechytsa',
    'Zhabinka',
    'Rahachow',
    'Horad Luninyets',
    'Vyalikaya Byerastavitsa',
    'Chashniki',
    'Shchuchyn',
    'Lyakhavichy',
    'Voranava',
    'Ivatsevichy',
    'Hantsavichy',
    'Drybin',
    'Shklow',
    'Horad Orsha',
    'Kastsyukovichy',
    'Karma',
    'Sharkawshchyna',
    'Bykhaw',
    'Chachersk',
    'Zhytkavichy',
    'Loyew',
    'Khotsimsk',
    'Chavusy',
    'Yel’sk',
    'Lyozna',
    'Hlusk',
    'Dokshytsy',
    'Aktsyabrski',
    'Krasnapollye',
    'Lyel’chytsy',
    'Brahin',
    'Rasony',
];
