export const NEW_ZEALAND_CITIES = [
    'Auckland',
    'Blenheim',
    'Christchurch',
    'Dunedin',
    'Gisborne',
    'Greymouth',
    'Hamilton',
    'Hastings',
    'Invercargill',
    'Lower Hutt',
    'Masterton',
    'Napier',
    'Nelson',
    'New Plymouth',
    'Palmerston North',
    'Porirua',
    'Rotorua',
    'Taupo',
    'Tauranga',
    'Timaru',
    'Upper Hutt',
    'Wellington',
    'Whanganui',
    'Whangarei',
];
