// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StyleModuleScssNamespace {
    export interface IStyleModuleScss {
        buttonWithIcon: string;
        buttonWithIconDisabled: string;
        buttonWithIconIcon: string;
        buttonWithIconTitle: string;
        buttonWithIconWithoutStyles: string;
        buttonWithIconWithoutStylesIcon: string;
    }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StyleModuleScssNamespace.IStyleModuleScss;
};

export = StyleModuleScssModule;
