// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesModuleScssNamespace {
    export interface IStylesModuleScss {
        kanbanColumn: string;
        kanbanColumnContent: string;
        kanbanColumnContentWrap: string;
        kanbanColumnEmptyBlock: string;
        kanbanColumnEmptyBlockDescription: string;
        kanbanColumnEmptyBlockTitle: string;
        kanbanColumnFooter: string;
        kanbanColumnFooterIcon: string;
        kanbanColumnHeader: string;
        kanbanColumnHeaderIcon: string;
        kanbanColumnHeaderIconDark: string;
        kanbanColumnHeaderTitle: string;
        kanbanEmptyColumn: string;
    }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StylesModuleScssNamespace.IStylesModuleScss;
};

export = StylesModuleScssModule;
